spring:
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: 'KEBAB_CASE'
    time-zone: 'UTC'
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'
