logging:
  level:
    x.etaggy: INFO
    root: WARN
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSX,UTC"

spring:
  application:
    name: etaggy
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: 'KEBAB_CASE'
    time-zone: 'UTC'
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'
