DROP TRIGGER insert_parent_version_t ON parent;
DROP TRIGGER update_parent_version_t ON parent;
DROP TRIGGER insert_child_version_t ON child;
DROP TRIGGER update_child_version_t ON child;
DROP TRIGGER insert_child_parent_t ON child;
DROP TRIGGER update_child_parent_t ON child;
DROP TRIGGER delete_child_parent_t ON child;
DROP FUNCTION insert_parent_version_f();
DROP FUNCTION update_parent_version_f();
DROP FUNCTION insert_child_version_f();
DROP FUNCTION update_child_version_f();
DROP FUNCTION insert_child_parent_f();
DROP FUNCTION update_child_parent_f();
DROP FUNCTION delete_child_parent_f();
DROP TABLE child;
DROP TABLE parent;
