feign:
  client:
    config:
      default:
        logger-level: 'FULL'

logbook:
  format:
    style: 'http'

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR
    org.zalando.logbook: TRACE
    x.loggy: DEBUG
    root: WARN
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSX,UTC"

loggy:
  enable-demo: true
  run-once: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: 'KEBAB_CASE'
    time-zone: 'UTC'
  main:
    banner-mode: 'OFF'
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: 'ALWAYS'
  resources:
    add-mappings: false  # NB -- not usable with Swagger
---

logbook:
  format:
    style: 'json'

spring:
  output:
    ansi:
      enabled: 'NEVER'
  profiles: json
