feign:
  client:
    config:
      default:
        logger-level: 'FULL'

logbook:
  format:
    style: 'http'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: 'KEBAB_CASE'
    time-zone: 'UTC'
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'

---

logbook:
  format:
    style: 'json'

logging:
  level:
    x.loggy: DEBUG
    root: INFO

spring:
  output:
    ansi:
      enabled: 'NEVER'
  profiles: json
