feign:
  client:
    config:
      default:
        logger-level: "FULL"

logbook:
  exclude:
    - /actuator/**
    - /ping
  format:
    style: "http"
  obfuscate:
    headers:
      - X-Secret-Value

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.postgresql: TRACE
    org.zalando.logbook: TRACE
    x.loggy: DEBUG
    x.loggy.LogPublicMethods: TRACE
    root: WARN
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSX,UTC"

loggy:
  enable-demo: true
  log-feign-retries: true
  run-once: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  application:
    name: loggy
  datasource:
    url: 'jdbc:postgresql:postgres?user=postgres&loggerLevel=DEBUG'
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: "KEBAB_CASE"
    time-zone: "UTC"
  main:
    banner-mode: "OFF"
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: "ALWAYS"
  resources:
    add-mappings: false  # NB -- not usable with Swagger

---

logbook:
  format:
    style: "json"

spring:
  output:
    ansi:
      enabled: "NEVER"
  profiles: json
