feign:
  client:
    config:
      default:
        # TODO: Somehow this corresponds to a Map.  What gives?
        logger-level: FULL

# Surprisingly, not under "management:"
info:
  app:
    # These are Maven-specific
    encoding: '@project.build.sourceEncoding@'
    java.source: '@java.version@'
    java.target: '@java.version@'

logbook:
  exclude:
    - /actuator/**
    - /ping
  format:
    style: "http"
  obfuscate:
    headers:
      - X-Secret-Value

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR
    org.zalando.logbook: TRACE
    x.loggy: DEBUG
    root: WARN
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSX,UTC"

loggy:
  enable-demo: true
  log-feign-retries: true
  run-once: true

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles:
        - 0.50
        - 0.68
        - 0.95
        - 0.997
      percentiles-histogram:
        all: true

server:
  port: 8080

spring:
  application:
    name: loggy
  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: postgres
  jackson:
    # TODO: Millis showing up anyways
    date-format: "yyyy-MM-dd'T'HH:mm:ssX"
    property-naming-strategy: "KEBAB_CASE"
    time-zone: "UTC"
  main:
    banner-mode: "OFF"
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: "ALWAYS"
  resources:
    add-mappings: false  # NB -- not usable with Swagger

---

logbook:
  format:
    style: "json"

spring:
  output:
    ansi:
      enabled: "NEVER"
  profiles: json
