cloud:
  aws:
    region:
      #      auto: true
      static: 'us-east-1'
    stack:
      auto: false
    credentials:
      access-key: foo
      secret-key: bar

logging:
  level:
    com.amazonaws.request: DEBUG
    com.example.demo: INFO
    org.springframework.cloud.aws: DEBUG
    root: WARN

localstack:
  enabled: true
  sqs:
    enabled: true

spring:
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'
