endpoints:
  all:
    path: /admin
  info:
    enabled: true
    sensitive: false

micronaut:
  application:
    name: micronaut-kitchen-sink
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
