endpoints:
  all:
    path: /admin
  info:
    enabled: true
    sensitive: false

logger:
  levels:
    root: INFO

micronaut:
  application:
    name: micronaut-kitchen-sink
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  router:
    static-resources:
      # TODO: What is the default path?
      homepage:
        paths: classpath:public
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
