CREATE TABLE SALLY
(
    id   INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE HOWARD
(
    id   INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE NANCY
(
    name      VARCHAR,
    howard_id INTEGER REFERENCES HOWARD (id)
);

CREATE TABLE SALLY_HOWARD
(
    sally_id  INTEGER REFERENCES SALLY (id),
    howard_id INTEGER REFERENCES HOWARD (id),
    PRIMARY KEY (sally_id, howard_id)
);
