version: '3'
services:
  healthy-spring-boot-logging:
    build:
      context: .
      dockerfile: healthy-spring-boot-logging-Dockerfile
    ports:
      - 8080:8080
  unhealthy-spring-boot-logging:
    build:
      context: .
      dockerfile: unhealthy-spring-boot-logging-Dockerfile
    ports:
      - 8079:8080
  prometheus:
    build:
      context: .
      dockerfile: prometheus-Dockerfile
    ports:
      - 9090:9090
