datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

endpoints:
  all:
    enabled: true
    path: /admin
    sensitive: false

swagger:
  path: /api-docs/swagger
  version: 3  # Latest version, let UI get improvements automatically
  layout: StandaloneLayout
  deepLinking: true
  displayRequestDuration: true
  showCommonExtensions: true
  showExtensions: true
  urls:
    - name: hello-world
      url: /api-docs/swagger/hello-world-0.1.yml

tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1

micronaut:
  application:
    name: hello-world
    instance: ${random.uuid}
    version: 0.1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: ${swagger.path}/**
