micronaut:
  application:
    name: hello-world
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      webjars:
        enabled: true
        paths: classpath:META-INF/resources/webjars/swagger-ui/3.22.2
        mapping: /swagger-ui/**
