datasources:
  default:
    dialect: H2
    driverClassName: org.h2.Driver
    password: ""
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MVCC=TRUE
    username: sa

endpoints:
  all:
    enabled: true
    path: /admin
    sensitive: false

flyway:
  datasources:
    default:
      dialect: H2
      driverClassName: org.h2.Driver
      password: ""
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MVCC=TRUE
      username: sa

swagger:
  path: /api-docs/swagger
  version: 3  # Latest version, let UI get improvements automatically
  layout: StandaloneLayout
  deepLinking: true
  displayRequestDuration: true
  showCommonExtensions: true
  showExtensions: true
  urls:
    - name: hello-world
      url: /api-docs/swagger/hello-world-0.1.yml

tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1

micronaut:
  application:
    name: hello-world
    instance: ${random.uuid}
    version: 0.1
  metrics:
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: ${swagger.path}/**
