logging:
  level:
    x: DEBUG
    root: WARN

spring:
  application:
    name: spring-boot-domain-persistence-modeling
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:postgres
    username: postgres
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'
