logging:
  level:
    org.springframework.jdbc.datasource:
      DataSourceTransactionManager: TRACE
    sql: TRACE
    x.txns: INFO
    root: WARN

spring:
  application:
    name: txns
  datasource:
    url: 'jdbc:postgresql:postgres?user=postgres'
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'
