logging:
  level:
    x.txns: INFO
    root: WARN

spring:
  application:
    name: txns
  datasource:
    platform: postgresql
    url: 'jdbc:postgresql:postgres?user=postgres'
  main:
    banner-mode: 'OFF'
  output:
    ansi:
      enabled: 'ALWAYS'
